/*   -*- buffer-read-only: t -*- vi: set ro:
 *
 *  DO NOT EDIT THIS FILE   (fsm-fsm.c)
 *
 *  It has been AutoGen-ed
 *  From the definitions    autogen/fsm.def
 *  and the template file   fsm
 *
 *  Automated Finite State Machine
 *
 *  Copyright (C) 1992-2018 Bruce Korb - all rights reserved
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name ``Bruce Korb'' nor the name of any other
 *    contributor may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * AutoFSM IS PROVIDED BY Bruce Korb ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL Bruce Korb OR ANY OTHER CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#define DEFINE_FSM
#include "fsm-fsm.h"
#include <stdio.h>

/*
 *  Do not make changes to this file, except between the START/END
 *  comments, or it will be removed the next time it is generated.
 */
/* START === USER HEADERS === DO NOT CHANGE THIS COMMENT */
/* END   === USER HEADERS === DO NOT CHANGE THIS COMMENT */

#ifndef NULL
#  define NULL 0
#endif

/**
 *  Callback routine prototype.  They return the next state.  Normally, that
 *  should be the value of the "maybe_next" argument.
 */
typedef te_fsm_state (fsm_callback_t)(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt );

static fsm_callback_t
    fsm_do_connection_established,
    fsm_do_connection_refused,
    fsm_do_establish_connection,
    fsm_do_invalid,
    fsm_do_log_bad_data_and_rset,
    fsm_do_log_bad_ehlo_and_close,
    fsm_do_log_bad_helo_and_close,
    fsm_do_log_bad_mail_from_and_ready,
    fsm_do_log_bad_message_and_rset,
    fsm_do_log_bad_quit_and_close,
    fsm_do_log_bad_rcpt_to_and_rset,
    fsm_do_log_good_data_and_message,
    fsm_do_log_good_ehlo_and_ready,
    fsm_do_log_good_helo_and_ready,
    fsm_do_log_good_mail_from_and_send_rcpt_to,
    fsm_do_log_good_message_and_message,
    fsm_do_log_good_message_and_ready,
    fsm_do_log_good_quit_and_close,
    fsm_do_log_good_rcpt_to_and_decide_rcpt_or_data,
    fsm_do_log_unreadable_data_and_rset,
    fsm_do_log_unreadable_ehlo_and_close,
    fsm_do_log_unreadable_helo_and_close,
    fsm_do_log_unreadable_mail_from_and_ready,
    fsm_do_log_unreadable_message_and_rset,
    fsm_do_log_unreadable_quit_and_close,
    fsm_do_log_unreadable_rcpt_to_and_rset,
    fsm_do_messages_not_found_and_quit,
    fsm_do_send_ehlo,
    fsm_do_send_helo,
    fsm_do_send_mail_from;

/**
 *  Declare all the state transition handling routines.
 */
typedef struct transition t_fsm_transition;
struct transition {
    te_fsm_state      next_state;
    fsm_callback_t *  trans_proc;
};

/**
 *  State transition maps.  Map the enumeration and the event enumeration
 *  to the new state and the transition enumeration code (in that order).
 *  It is indexed by first the current state and then the event code.
 */
static const t_fsm_transition
fsm_trans_table[ FSM_STATE_CT ][ FSM_EVENT_CT ] = {

  /* STATE 0:  FSM_ST_INIT */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  GOOD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  BAD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 1:  FSM_ST_CLOSED */
  { { FSM_ST_CONNECTING, fsm_do_establish_connection }, /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  GOOD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  BAD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 2:  FSM_ST_CONNECTING */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_CONNECTED, fsm_do_connection_established }, /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_CLOSED, fsm_do_connection_refused },   /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  GOOD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  BAD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 3:  FSM_ST_CONNECTED */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  GOOD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  BAD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_SENDING_HELO, fsm_do_send_helo },      /* EVT:  SEND_HELO */
    { FSM_ST_SENDING_EHLO, fsm_do_send_ehlo },      /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 4:  FSM_ST_READY */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  GOOD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  BAD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_SENDING_QUIT, fsm_do_messages_not_found_and_quit }, /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_SENDING_MAIL_FROM, fsm_do_send_mail_from }, /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 5:  FSM_ST_SENDING_HELO */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_READY, fsm_do_log_good_helo_and_ready }, /* EVT:  GOOD_RESPONSE */
    { FSM_ST_CLOSED, fsm_do_log_bad_helo_and_close }, /* EVT:  BAD_RESPONSE */
    { FSM_ST_CLOSED, fsm_do_log_unreadable_helo_and_close }, /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 6:  FSM_ST_SENDING_EHLO */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_READY, fsm_do_log_good_ehlo_and_ready }, /* EVT:  GOOD_RESPONSE */
    { FSM_ST_CLOSED, fsm_do_log_bad_ehlo_and_close }, /* EVT:  BAD_RESPONSE */
    { FSM_ST_CLOSED, fsm_do_log_unreadable_ehlo_and_close }, /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 7:  FSM_ST_SENDING_MAIL_FROM */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_SENDING_RCPT, fsm_do_log_good_mail_from_and_send_rcpt_to }, /* EVT:  GOOD_RESPONSE */
    { FSM_ST_READY, fsm_do_log_bad_mail_from_and_ready }, /* EVT:  BAD_RESPONSE */
    { FSM_ST_READY, fsm_do_log_unreadable_mail_from_and_ready }, /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 8:  FSM_ST_SENDING_RCPT_TO */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_NEED_TO_RCPT_OR_DATA, fsm_do_log_good_rcpt_to_and_decide_rcpt_or_data }, /* EVT:  GOOD_RESPONSE */
    { FSM_ST_SENDING_RSET, fsm_do_log_bad_rcpt_to_and_rset }, /* EVT:  BAD_RESPONSE */
    { FSM_ST_SENDING_RSET, fsm_do_log_unreadable_rcpt_to_and_rset }, /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 9:  FSM_ST_NEED_TO_RCPT_TO_OR_DATA */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  GOOD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  BAD_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 10:  FSM_ST_SENDING_DATA */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_SENDING_MESSAGE, fsm_do_log_good_data_and_message }, /* EVT:  GOOD_RESPONSE */
    { FSM_ST_SENDING_RSET, fsm_do_log_bad_data_and_rset }, /* EVT:  BAD_RESPONSE */
    { FSM_ST_SENDING_RSET, fsm_do_log_unreadable_data_and_rset }, /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 11:  FSM_ST_SENDING_MESSAGE */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_READY, fsm_do_log_good_message_and_ready }, /* EVT:  GOOD_RESPONSE */
    { FSM_ST_SENDING_RSET, fsm_do_log_bad_message_and_rset }, /* EVT:  BAD_RESPONSE */
    { FSM_ST_SENDING_RSET, fsm_do_log_unreadable_message_and_rset }, /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_SENDING_MESSAGE, fsm_do_log_good_message_and_message }, /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  },

  /* STATE 12:  FSM_ST_SENDING_QUIT */
  { { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  ESTABLISH_CONNECTION */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_ESTABLISHED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_REFUSED */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  CONNECTION_CLOSED_BY_REMOTE */
    { FSM_ST_CLOSED, fsm_do_log_good_quit_and_close }, /* EVT:  GOOD_RESPONSE */
    { FSM_ST_CLOSED, fsm_do_log_bad_quit_and_close }, /* EVT:  BAD_RESPONSE */
    { FSM_ST_CLOSED, fsm_do_log_unreadable_quit_and_close }, /* EVT:  UNREADABLE_RESPONSE */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  NO_MORE_MESSAGES */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_HELO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_EHLO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MAIL_FROM */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_RCPT_TO */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_DATA */
    { FSM_ST_INVALID, fsm_do_invalid },             /* EVT:  SEND_MESSAGE */
    { FSM_ST_INVALID, fsm_do_invalid }              /* EVT:  SEND_QUIT */
  }
};

/**
 *  The FSM machine state
 */
static te_fsm_state fsm_state = FSM_ST_INIT;


#define FsmFsmErr_off     19
#define FsmEvInvalid_off  75
#define FsmStInit_off     83


static char const zFsmStrings[484] =
/*     0 */ "** OUT-OF-RANGE **\0"
/*    19 */ "FSM Error:  in state %d (%s), event %d (%s) is invalid\n\0"
/*    75 */ "invalid\0"
/*    83 */ "init\0"
/*    88 */ "closed\0"
/*    95 */ "connecting\0"
/*   106 */ "connected\0"
/*   116 */ "ready\0"
/*   122 */ "sending_helo\0"
/*   135 */ "sending_ehlo\0"
/*   148 */ "sending_mail_from\0"
/*   166 */ "sending_rcpt_to\0"
/*   182 */ "need_to_rcpt_to_or_data\0"
/*   206 */ "sending_data\0"
/*   219 */ "sending_message\0"
/*   235 */ "sending_quit\0"
/*   248 */ "establish_connection\0"
/*   269 */ "connection_established\0"
/*   292 */ "connection_refused\0"
/*   311 */ "connection_closed_by_remote\0"
/*   339 */ "good_response\0"
/*   353 */ "bad_response\0"
/*   366 */ "unreadable_response\0"
/*   386 */ "no_more_messages\0"
/*   403 */ "send_helo\0"
/*   413 */ "send_ehlo\0"
/*   423 */ "send_mail_from\0"
/*   438 */ "send_rcpt_to\0"
/*   451 */ "send_data\0"
/*   461 */ "send_message\0"
/*   474 */ "send_quit";

static const size_t aszFsmStates[13] = {
    83,  88,  95,  106, 116, 122, 135, 148, 166, 182, 206, 219, 235 };

static const size_t aszFsmEvents[16] = {
    248, 269, 292, 311, 339, 353, 366, 386, 403, 413, 423, 438, 451, 461, 474,
    75 };


#define FSM_EVT_NAME(t)   ( (((unsigned)(t)) >= 16) \
    ? zFsmStrings : zFsmStrings + aszFsmEvents[t])

#define FSM_STATE_NAME(s) ( (((unsigned)(s)) >= 13) \
    ? zFsmStrings : zFsmStrings + aszFsmStates[s])

#ifndef EXIT_FAILURE
# define EXIT_FAILURE 1
#endif

static int fsm_invalid_transition( te_fsm_state st, te_fsm_event evt );

/* * * * * * * * * THE CODE STARTS HERE * * * * * * * */
/**
 *  Print out an invalid transition message and return EXIT_FAILURE
 */
static int
fsm_invalid_transition( te_fsm_state st, te_fsm_event evt )
{
    /* START == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */
    char const * fmt = zFsmStrings + FsmFsmErr_off;
    fprintf( stderr, fmt, st, FSM_STATE_NAME(st), evt, FSM_EVT_NAME(evt));
    /* END   == INVALID TRANS MSG == DO NOT CHANGE THIS COMMENT */

    return EXIT_FAILURE;
}

static te_fsm_state
fsm_do_connection_established(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == CONNECTION ESTABLISHED == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == CONNECTION ESTABLISHED == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_connection_refused(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == CONNECTION REFUSED == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == CONNECTION REFUSED == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_establish_connection(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == ESTABLISH CONNECTION == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == ESTABLISH CONNECTION == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_invalid(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == INVALID == DO NOT CHANGE THIS COMMENT  */
    exit(fsm_invalid_transition(initial, trans_evt));
/*  END   == INVALID == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_bad_data_and_rset(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG BAD DATA AND RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG BAD DATA AND RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_bad_ehlo_and_close(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG BAD EHLO AND CLOSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG BAD EHLO AND CLOSE == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_bad_helo_and_close(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG BAD HELO AND CLOSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG BAD HELO AND CLOSE == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_bad_mail_from_and_ready(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG BAD MAIL FROM AND READY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG BAD MAIL FROM AND READY == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_bad_message_and_rset(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG BAD MESSAGE AND RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG BAD MESSAGE AND RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_bad_quit_and_close(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG BAD QUIT AND CLOSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG BAD QUIT AND CLOSE == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_bad_rcpt_to_and_rset(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG BAD RCPT TO AND RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG BAD RCPT TO AND RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_good_data_and_message(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG GOOD DATA AND MESSAGE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG GOOD DATA AND MESSAGE == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_good_ehlo_and_ready(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG GOOD EHLO AND READY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG GOOD EHLO AND READY == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_good_helo_and_ready(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG GOOD HELO AND READY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG GOOD HELO AND READY == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_good_mail_from_and_send_rcpt_to(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG GOOD MAIL FROM AND SEND RCPT TO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG GOOD MAIL FROM AND SEND RCPT TO == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_good_message_and_message(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG GOOD MESSAGE AND MESSAGE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG GOOD MESSAGE AND MESSAGE == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_good_message_and_ready(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG GOOD MESSAGE AND READY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG GOOD MESSAGE AND READY == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_good_quit_and_close(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG GOOD QUIT AND CLOSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG GOOD QUIT AND CLOSE == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_good_rcpt_to_and_decide_rcpt_or_data(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG GOOD RCPT TO AND DECIDE RCPT OR DATA == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG GOOD RCPT TO AND DECIDE RCPT OR DATA == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_unreadable_data_and_rset(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG UNREADABLE DATA AND RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG UNREADABLE DATA AND RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_unreadable_ehlo_and_close(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG UNREADABLE EHLO AND CLOSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG UNREADABLE EHLO AND CLOSE == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_unreadable_helo_and_close(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG UNREADABLE HELO AND CLOSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG UNREADABLE HELO AND CLOSE == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_unreadable_mail_from_and_ready(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG UNREADABLE MAIL FROM AND READY == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG UNREADABLE MAIL FROM AND READY == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_unreadable_message_and_rset(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG UNREADABLE MESSAGE AND RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG UNREADABLE MESSAGE AND RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_unreadable_quit_and_close(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG UNREADABLE QUIT AND CLOSE == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG UNREADABLE QUIT AND CLOSE == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_log_unreadable_rcpt_to_and_rset(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == LOG UNREADABLE RCPT TO AND RSET == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == LOG UNREADABLE RCPT TO AND RSET == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_messages_not_found_and_quit(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == MESSAGES NOT FOUND AND QUIT == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == MESSAGES NOT FOUND AND QUIT == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_send_ehlo(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == SEND EHLO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SEND EHLO == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_send_helo(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == SEND HELO == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SEND HELO == DO NOT CHANGE THIS COMMENT  */
}

static te_fsm_state
fsm_do_send_mail_from(
    SMTPConnectionList *head, SMTPConnection *connection,
    te_fsm_state initial,
    te_fsm_state maybe_next,
    te_fsm_event trans_evt)
{
/*  START == SEND MAIL FROM == DO NOT CHANGE THIS COMMENT  */
    return maybe_next;
/*  END   == SEND MAIL FROM == DO NOT CHANGE THIS COMMENT  */
}

/**
 *  Step the FSM.  Returns the resulting state.  If the current state is
 *  FSM_ST_DONE or FSM_ST_INVALID, it resets to
 *  FSM_ST_INIT and returns FSM_ST_INIT.
 */
te_fsm_state
fsm_step(
    te_fsm_event trans_evt,
    SMTPConnectionList *head, SMTPConnection *connection )
{
    te_fsm_state nxtSt;
    fsm_callback_t * pT;

    if ((unsigned)fsm_state >= FSM_ST_INVALID) {
        fsm_state = FSM_ST_INIT;
        return FSM_ST_INIT;
    }

#ifndef __COVERITY__
    if (trans_evt >= FSM_EV_INVALID) {
        nxtSt = FSM_ST_INVALID;
        pT    = fsm_do_invalid;
    } else
#endif /* __COVERITY__ */
    {
        const t_fsm_transition * ttbl =
            fsm_trans_table[ fsm_state ] + trans_evt;
        nxtSt = ttbl->next_state;
        pT    = ttbl->trans_proc;
    }

    if (pT != NULL)
        nxtSt = (*pT)( connection, fsm_state, nxtSt, trans_evt );

    fsm_state = nxtSt;

    /* START == FINISH STEP == DO NOT CHANGE THIS COMMENT */
    /* END   == FINISH STEP == DO NOT CHANGE THIS COMMENT */

    return nxtSt;
}
/*
 * Local Variables:
 * mode: C
 * c-file-style: "stroustrup"
 * indent-tabs-mode: nil
 * End:
 * end of fsm-fsm.c */
