name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install_cunit_macOS
      run: brew install cunit
    
    - name: clean
      run: make clean
      
    - name: make
      run: make
  
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install_cunit_macOS
      run: brew install cunit
    
    - name: clean
      run: make clean
      
    - name: make-test
      run: make test
      
    - name: test
      run: build/test/test
    
